# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-20 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bond_rating_scale_lgd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Scale_grade', models.CharField(max_length=50, verbose_name='LGD\u7ea7\u522b')),
                ('low_bound', models.FloatField(max_length=50, verbose_name='\u4e0b\u754c')),
                ('upper_bound', models.FloatField(max_length=50, verbose_name='\u4e0a\u754c')),
            ],
        ),
        migrations.CreateModel(
            name='Bond_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=50, verbose_name='\u503a\u9879\u7c7b\u578b')),
                ('Coefficient', models.FloatField(max_length=50, verbose_name='\u7cfb\u6570')),
            ],
        ),
        migrations.CreateModel(
            name='Collateral_control',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=50, verbose_name='\u62b5\u8d28\u62bc\u54c1\u63a7\u5236\u529b')),
                ('Coefficient', models.FloatField(max_length=50, verbose_name='\u7cfb\u6570')),
            ],
        ),
        migrations.CreateModel(
            name='Collateral_depend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=50, verbose_name='\u62b5\u8d28\u62bc\u54c1\u72ec\u7acb\u6027')),
                ('Coefficient', models.FloatField(max_length=50, verbose_name='\u7cfb\u6570')),
            ],
        ),
        migrations.CreateModel(
            name='Collateral_environment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=50, verbose_name='\u62b5\u8d28\u62bc\u54c1\u6267\u6cd5\u73af\u5883')),
                ('Coefficient', models.FloatField(max_length=50, verbose_name='\u7cfb\u6570')),
            ],
        ),
        migrations.CreateModel(
            name='Collateral_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=50, verbose_name='\u62b5\u8d28\u62bc\u54c1\u7c7b\u578b')),
                ('Coefficient', models.FloatField(max_length=50, verbose_name='\u7cfb\u6570')),
            ],
        ),
        migrations.CreateModel(
            name='Company_nature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=50, verbose_name='\u4f01\u4e1a\u6027\u8d28\u7c7b\u578b')),
                ('Coefficient', models.FloatField(max_length=50, verbose_name='\u7cfb\u6570')),
            ],
        ),
        migrations.CreateModel(
            name='Credit_environment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=50, verbose_name='\u4fe1\u7528\u73af\u5883')),
                ('Coefficient', models.FloatField(max_length=50, verbose_name='\u7cfb\u6570')),
            ],
        ),
        migrations.CreateModel(
            name='Guarantee_strength',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=50, verbose_name='\u62c5\u4fdd\u5f3a\u5ea6')),
                ('Coefficient', models.FloatField(max_length=50, verbose_name='\u7cfb\u6570')),
            ],
        ),
        migrations.CreateModel(
            name='Guarantee_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=50, verbose_name='\u62c5\u4fdd\u7c7b\u578b')),
                ('Coefficient', models.FloatField(max_length=50, verbose_name='\u7cfb\u6570')),
            ],
        ),
        migrations.CreateModel(
            name='Guarantor_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=50, verbose_name='\u62c5\u4fdd\u4eba\u7c7b\u578b')),
                ('Coefficient', models.FloatField(max_length=50, verbose_name='\u7cfb\u6570')),
            ],
        ),
        migrations.CreateModel(
            name='Issuer_industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=50, verbose_name='\u53d1\u884c\u4eba\u884c\u4e1a\u7c7b\u578b')),
                ('Coefficient', models.FloatField(max_length=50, verbose_name='\u7cfb\u6570')),
            ],
        ),
        migrations.CreateModel(
            name='ratting_master_scale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ratting', models.CharField(max_length=50, verbose_name='\u8bc4\u7ea7\u7ed3\u679c')),
                ('Min_val', models.FloatField(max_length=50, verbose_name='\u6700\u5c0f\u503c')),
                ('Max_val', models.FloatField(max_length=50, verbose_name='\u6700\u5927\u503c')),
            ],
        ),
    ]
